### ISSUE TITLE
Agregar permiso de Write a BS de colecciones en Digesto

### ISSUE THREAD

**Issue by PabloDeAlbu** [crai-unrn/DSpace#3]
Se tiene un grupo con permisos de write sobre una colección dentro de la comunidad Digesto.
Si bien aparece el formulario de edición, a la hora de reflejar los cambios aparece el siguiente error

```apache
INFO  org.dspace.app.webui.servlet.DSpaceServlet @ pablo+digesto@sedici.unlp.edu.ar:session_id=C616698D9A8D242CEF44E87A23B7F798:ip_addr=0:0:0:0:0:0:0:1:authorize_error:org.dspace.authorize.AuthorizeException\colon; Authorization denied for action WRITE on BITSTREAM\colon;1 by user 6
```
Agregar permiso de WRITE para BITSTREAM para el grupo digesto en las colección necesarias.
Anotar en este ticket que permisos fueron creados cuales fueron las colecciones involucradas

**Comment by Camila-C** [comment]
Se añadieron permisos de WRITE para BITSTREAM al grupo Digesto para las colecciones:
- RID-UNRN > Digesto > Resoluciones UNRN > Resoluciones CDEYVE
- RID-UNRN > Digesto > Resoluciones UNRN > Resoluciones CICADyTT
- RID-UNRN > Digesto > Resoluciones UNRN > Resoluciones CPYGE
- RID-UNRN > Digesto > Resoluciones UNRN > Resoluciones Rectorales
- RID-UNRN > Digesto > Resoluciones UNRN > Resoluciones UNRN
